- name: Copy filebeat yum repo
  ansible.builtin.template:
    src: filebeat.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy Filebeat Config
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes