- name: Copy Logstash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes

- name: wait for logstash to run
  ansible.builtin.wait_for:
    port: 5044
    timeout: 180
    delay: 30