- name: Copy mysql Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MYSQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Restart MYSQL service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Check root default password
  block:
    - name: Get MYSQL version to check th DB connection
      mysql_info:
        login_user: root
        login_password: "{{MYSQL_PASSWORD}}"
        filter: version
  rescue:
    - name: Load mysql log file
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: Declare Facts
      ansible.builtin.set_fact:
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') |split(' ') | last }}"

    - name: Change MYSQL password
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"

- name: Check Validate plugin exists
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p{{MYSQL_PASSWORD}}
  ignore_errors: yes

- name: Download MySQL Schema files
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"