- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Copy Alert Rules Configuration
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml
  notify: Restart Prometheus

- name: Start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes

- name: wait for prometheus to start
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 30

- name: Copy Alert Manager Configuration file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart Alert Manager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Wait for Alertmanager to start
  ansible.builtin.wait_for:
    port: 9093
    delay: 10
    timeout: 30